### ISSUE TITLE
Adding yaml templating functionality for configs.

### ISSUE THREAD

**Issue by vishnuchalla** [cloud-bulldozer/orion#38]
### Description
As of today we have some example configs along with the ones for 4.15, that will help us fetch some of the key control and data plane metrics used for our release readouts. But preparing the same for a different version, requires re-work.

### Acceptance criteria
So as solution we need yaml templating support. As a user one should be able to leverage yaml templating functionality to come up with their own templates and update them during the runtime.

cc: @shashank-boyapally @paigerube14 @jtaleric

**Comment by shashank-boyapally** [comment]
This has been introduced in daemon mode, do we want this in cmd mode as well?

**Comment by vishnuchalla** [comment]
Yes need it everywhere in orion.

**Comment by shashank-boyapally** [comment]
Closing since merged
