### ISSUE TITLE
 Add functionality tests to orion

### ISSUE THREAD

**Issue by vishnuchalla** [cloud-bulldozer/orion#51]
### Description
 Add functionality tests to orion to make sure all the test configs work as expected. This will help us detect any breaking components in early stages itself (i.e in PR’s github actions).

### Acceptance Criteria
As a contributor when I raise a PR, I should be able to see all the breaking components in the early stages itself so that I will have a smoother experience in the CI system.

**Comment by shashank-boyapally** [comment]
Closing this since tests are already present.
