### ISSUE TITLE
[RFE] Once a a change point is detected provide a way to query additional metadata

### ISSUE THREAD

**Issue by smalleni** [cloud-bulldozer/orion#8]
Based on the provided fingerprint/metadata, the results are queried, passed to hunter and a change point is identified which means the performance changed significantly between two specific runs. It would be nice to get additional metadata corresponding to those runs that can identify things like the nightly of the run etc.

**Comment by shashank-boyapally** [comment]
Added build URL which directs to the metadata of the run, Please let me know if we  still want a way to query metadata directly on command line.
